=== skitzke/Spring-rest-api.java/src/main/java/com/example/demo/schemas/netflix/netflix_valid.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Netflix",
  "description": "Information on every movie in Netflix",
  "type": "object",
  "properties": {
    "show_id": {
      "type": "integer"
    },
    "type": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "director": {
      "type": "string"
    },
    "cast": {
      "type": "string"
    },
    "country": {
      "type": "string"
    },
    "date_added": {
      "type": "string",
      "pattern": "(0?[1-9]|[12]\\d|30|31)-[A-Z][a-z][a-z]-[0-9][0-9]"
    },
    "release_year": {
      "type": "integer",
      "minLength": 4
    },
    "rating": {
      "type": "string",
      "enum": ["TV-Y","TV-Y7","G","TV-G","PG","TV-PG","PG-13","TV-14","R","TV-MA","NC-17"]
    },
    "duration": {
      "type": "string"
    },
    "listed_in": {
      "type": "string"
    },
    "description": {
      "type": "string"
    }
  },
  "required": [
    "show_id",
    "type",
    "title",
    "director",
    "cast",
    "country",
    "date_added",
    "release_year",
    "rating",
    "duration",
    "listed_in",
    "description"
  ]
}

=== skitzke/Spring-rest-api.java/src/main/java/com/example/demo/schemas/netflix/netflix.json
{
  "show_id": 8381939,
  "type": "TV Show",
  "title": "Leslie Jones: Time Machine",
  "director": "Tod Philips",
  "cast": "Charlie Sheen",
  "country": "United States",
  "date_added": "10-Jan-20",
  "release_year": 2020,
  "rating": "TV-14",
  "duration": "1 Season",
  "listed_in": "TV Comedies, TV Dramas",
  "description": "When an 11 year old girl disappears...."
}
